bug:
  - "bug"
documentation:
  - "docs"
  - "documentation"
duplicate:
  - "duplicate"
enhancement:
  - "enhancement"
good first issue:
  - "good first issue"
  - "beginner"
help wanted:
  - "help wanted"
  - "help"
invalid:
  - "invalid"
question:
  - "question"
wontfix:
  - "wontfix"
