name: Icons Management

on:
  push:
    paths:
      - "icons/**"
  workflow_dispatch:

jobs:
  process-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Image Processing Tools
        run: npm install imagemin imagemin-cli

      - name: Optimize Icons
        run: npx imagemin icons/* --out-dir=dist/icons
