name: Run Commands

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  run-command-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Command 1
        run: chmod +x scripts/deploy.sh

      - name: Run Command 2
        run: ./scripts/deploy.sh staging

      - name: Run Command 3
        run: ./scripts/deploy.sh production
